CREATE DATABASE ShopDB;
USE ShopDB;

CREATE TABLE `SELLER` (
    `SELLER_NAME` varchar(10) NOT NULL,
    `REAL_NAME` varchar(10) NOT NULL,
    `PHONE_NUM` varchar(15) NOT NULL,
    `ACCOUNT` varchar(20) NOT NULL,
    `PASSWORD` varchar(20) NOT NULL,
    `ADDRESS` varchar(90) NOT NULL,
    PRIMARY KEY (`SELLER_NAME`),
    UNIQUE KEY `ACCOUNT_UNIQUE` (`ACCOUNT`)
);

CREATE TABLE `USER` (
    `USER_NAME` varchar(10) NOT NULL,
    `PHONE_NUM` varchar(15) NOT NULL,
    `ACCOUNT` varchar(20) NOT NULL,
    `PASSWORD` varchar(20) NOT NULL,
    PRIMARY KEY (`USER_NAME`),
    UNIQUE KEY `ACCOUNT_UNIQUE` (`ACCOUNT`)
);

CREATE TABLE `POST` (
    `POST_TITLE` varchar(20) NOT NULL,
    `CONTENT` varchar(90) DEFAULT '`No content`',
    `STARTDATE` date DEFAULT (now()),
    `ENDDATE` date NOT NULL DEFAULT '2033-12-31',
    `LEGAL` tinyint GENERATED ALWAYS AS (
        (
            case
                when ((to_days(`ENDDATE`) - to_days(`STARTDATE`)) < 0) then 0
                else 1
            end
        )
    ) VIRTUAL,
    `SELLER_NAME` varchar(10) DEFAULT NULL,
    PRIMARY KEY (`POST_TITLE`),
    KEY `SELLER_NAME_idx` (`SELLER_NAME`),
    CONSTRAINT `SELLER_NAME` FOREIGN KEY (`SELLER_NAME`) REFERENCES `SELLER` (`SELLER_NAME`) ON DELETE RESTRICT ON UPDATE RESTRICT
);

CREATE TABLE `ITEM` (
    `ITEM_ID` int NOT NULL AUTO_INCREMENT,
    `NAME` varchar(30) DEFAULT 'no name',
    `PRICE` int NOT NULL DEFAULT '1' COMMENT '一元起標',
    `DISCRIPTION` varchar(45) DEFAULT 'no discription',
    `INVENTORY` int NOT NULL DEFAULT '1',
    `CATEGORY` varchar(20) DEFAULT 'no category',
    `IMAGE` varchar(100) NOT NULL,
    `POST_TITLE` varchar(20) NOT NULL,
    PRIMARY KEY (`ITEM_ID`),
    KEY `POST_TITLE_idx` (`POST_TITLE`),
    CONSTRAINT `POST_TITLE` FOREIGN KEY (`POST_TITLE`) REFERENCES `POST` (`POST_TITLE`) ON DELETE CASCADE ON UPDATE RESTRICT
);

CREATE TABLE `BID` (
    `BID_ID` int NOT NULL AUTO_INCREMENT,
    `PRICE` int NOT NULL DEFAULT '1',
    `QUANTITY` int DEFAULT '1',
    `ITEM_ID` int NOT NULL,
    `USER_NAME` varchar(10) NOT NULL,
    PRIMARY KEY (`BID_ID`),
    KEY `ITEM_ID_idx` (`ITEM_ID`),
    KEY `USER_NAME_idx` (`USER_NAME`),
    CONSTRAINT `ITEM_ID` FOREIGN KEY (`ITEM_ID`) REFERENCES `ITEM` (`ITEM_ID`) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT `USER_NAME` FOREIGN KEY (`USER_NAME`) REFERENCES `USER` (`USER_NAME`) ON DELETE RESTRICT ON UPDATE RESTRICT
);

CREATE TABLE `v_FORSALE` (
    `POST_TITLE` varchar(20) NOT NULL,
    `IS_FORSALE` int NOT NULL DEFAULT '0'
);