import mysql from "mysql"

export const getRates = async (req, res) => {
  /* #swagger.tags = ['Rates']
  #swagger.description = 'Get who's tracking this item' */
  var query = `
  SELECT track_user_name FROM ITEM JOIN TRACK ON track_item_id = item_id 
  JOIN POST ON item_post_title = post_title WHERE post_title =?`;

  var db = mysql.createConnection({
    // connectTimeout  : 60 * 60 * 1000,
    // Change it to the public IP generated by ngrok
    host: "127.0.0.1",
    port: process.env.DB_PORT,
    user: "root",
    password: "123456",
    database: "ShopDB",
    multipleStatements: true
  })
  db.connect();
  
  var string_ = req.params.title.replace('}', '')
  db.query(query, [string_], (err, rows) => {
    if (err) throw err;
    console.log(rows)
    return res.status(200).json({ tracks: rows });
    })
  // db.end();
}