import mysql from "mysql"

export const addPost = async (req, res) => {
    const seller = req.body.myName
    const post_title = req.body.title
    const content = req.body.content
    const price = req.body.price
    const img = req.body.img
    /* #swagger.tags = ['Posts']
    #swagger.description = 'Add a new post' */
    var query = `INSERT INTO POST (post_title, content, post_seller_name) VALUES ( ? , ? , ?);
    INSERT INTO ITEM (price, image, item_post_title) VALUES (?,?,?);
    `;

    var db = mysql.createConnection({
        // Change it to the public IP generated by ngrok
        host: "127.0.0.1",
        port: process.env.DB_PORT,
        user: "root",
        password: "123456",
        database: "ShopDB",
        multipleStatements: true
    })

    db.connect();
    console.log(seller)
    db.query(query, [post_title, content, seller, price, img, post_title], (err, rows) => {
        if (err) throw err
        // console.log(`SQL query: ${query}`)
        // console.log(rows)
        return res.status(200).json({ message: "Success!" });
    });
    db.end();
}