import mysql from "mysql"

export const deletePost = async (req, res) => {
  /* #swagger.tags = ['Posts']
  #swagger.description = 'Delete certain post' */
  var query = 'DELETE FROM POST WHERE post_title = ? ';

  // 模板語法: `stringstring str str ${variable}` // 要是``，"" 沒有模板語法


  var db = mysql.createConnection({
    // Change it to the public IP generated by ngrok
    host: "127.0.0.1",
    port: process.env.DB_PORT,
    user: "root",
    password: "123456",
    database: "ShopDB"
  })

  db.connect();
  db.query(query, [req.params.title], async (err, rows, fields) => {
    if (err) throw err;
    return res.status(200).json({ message: "Success!" });
    })
  db.end();
};
