import mysql from "mysql"

export const getAllPosts = async (req, res) => {
  /* #swagger.tags = ['Posts']
  #swagger.description = 'Get all posts' */
  var query = `
  SELECT * FROM ITEM INNER JOIN POST ON ITEM.POST_TITLE = POST.POST_TITLE;`;

  var db = mysql.createConnection({
    // connectTimeout  : 60 * 60 * 1000,
    // Change it to the public IP generated by ngrok
    host: "127.0.0.1",
    port: process.env.DB_PORT,
    user: "root",
    password: "123456",
    database: "shoppingDB",
    multipleStatements: true
  })
  db.connect();

  var allbids;
  const postBids = async (post_name) => {
    var query_bid = `SELECT * FROM ITEM JOIN BID ON ITEM.ITEM_ID = BID.ITEM_ID
    JOIN POST ON ITEM.POST_TITLE = ?`;
    await db.query(query_bid, [post_name], (err, rows, fields) => {
      if (err) throw err;
      allbids = rows.map((row) => {
        return {
          whoBids: row.USER_NAME,
          bPrice: row.PRICE
        }
      })
    })
    console.log(allbids)
    return allbids
  };

  db.query(query, (err, rows, fields) => {
    if (err) throw err;
    // console.log(rows)
    const allPosts = rows.map(async (row) => {
      var bids = await postBids(row.POST_TITLE)
      console.log(bids)
      return {
        postSeller: row.SELLER_NAME,
        postTitle: row.POST_TITLE,
        postContent: row.CONTENT,
        recommendedPrice: row.PRICE, // 還沒拿到
        postImg: row.IMAGE, // 還沒拿到
        bidPrices: bids
      }
    })
    return res.status(200).json({ posts: allPosts });
    // console.log(`allPosts:\n`)
    // console.log(allPosts)
  });
  // db.end();
}