import mysql from "mysql"

export const getAllPosts = async (req, res) => {
  /* #swagger.tags = ['Posts']
  #swagger.description = 'Get all posts' */
  var query = 'SELECT * FROM POST';

  var db = mysql.createConnection({
    // connectTimeout  : 60 * 60 * 1000,
    // Change it to the public IP generated by ngrok
    host: "127.0.0.1",
    port: process.env.DB_PORT,
    user: "root",
    password: "123456",
    database: "shoppingDB"
  })
  db.connect();
  db.query(query, function (err, rows, fields) {
    if (err) throw err;
    // res.render('index', { title: '這是 mysql + node.js 示範版本', 'items': rows });   
    return res.status(200).json(rows);
  });
  db.end();
}