import mysql from "mysql"

export const getBid = async (req, res) => {
  /* #swagger.tags = ['Bids']
  #swagger.description = 'Get bids from one post' */
  var query = `
  SELECT * FROM ITEM JOIN BID ON item_id = bid_item_id 
  JOIN POST ON item_post_title = post_title WHERE post_title =?`;

  var db = mysql.createConnection({
    // connectTimeout  : 60 * 60 * 1000,
    // Change it to the public IP generated by ngrok
    host: "127.0.0.1",
    port: process.env.DB_PORT,
    user: "root",
    password: "123456",
    database: "ShopDB",
    multipleStatements: true
  })
  db.connect();
  
  var string_ = req.params.title.replace('}', '')
  db.query(query, [string_], (err, rows) => {
    if (err) throw err;
    console.log(rows)
    const allbids = rows.map((row) => {
      return {
        whoBids: row.bid_user_name,
        bPrice: row.price
      }
    })
    Promise.all(allbids).then((results)=>{
      console.log(results)
      return res.status(200).json({ bids: results });
    })
  })
  // db.end();
}