import mysql from "mysql"

export const getSearchPosts = async (req, res) => {
  /* #swagger.tags = ['Posts']
  #swagger.description = 'Search posts' */
  var query = 'SELECT * FROM ITEM INNER JOIN POST ON ITEM.POST_TITLE = POST.POST_TITLE WHERE POST.POST_TITLE = ? ';

  var db = mysql.createConnection({
    // Change it to the public IP generated by ngrok
    host: "127.0.0.1",
    port: process.env.DB_PORT,
    user: "root",
    password: "123456",
    database: "ShopDB"
  })

  db.connect();
  db.query(query, [req.params.title], async (err, rows, fields) => {
    if (err) throw err;
    
    const allPosts = rows.map(async (row) => {
      return {
        postSeller: row.SELLER_NAME,
        postTitle: row.POST_TITLE,
        postContent: row.CONTENT,
        recommendedPrice: row.PRICE, 
        postImg: row.IMAGE, 
      }
    })

    Promise.all(allPosts).then((results) => {
      console.log(results)
      return res.status(200).json({ posts: results });
    })
  });
  db.end();
}